---
title: "Week 01: Introduction to Geospatial Data"
author: "Jude Bayham"
format: 
  html:
    theme: zephyr
    toc: true
---

<!-- flashy geospatial image -->

## Introduction

The objective of this workshop is to introduce you to geospatial data. You will acquire, assemble, process, and map spatial data.

## Prerequisites

### Statistics Japan

We will access data from <https://www.e-stat.go.jp/> using their application programming interface (API). You will need to register for an API key in order to use the API. These were the instructions and link names in English. I will update these with instructions in Japanese.

  1. Follow the links to create an account.   
  
  2. Click the link to "My Page".
  
  3. Click the link to "API function (application ID issuance)"
  
  4. Complete the fields name (a name for your application: Rscript) and URL (http://test.localhost/)
  
  5. Click "issue" to the right
  
  6. The appID field should now contain a long string of numbers and letters. This is the key associated with your account. You will use this to query data through the API.
  
  7. Set appID as an environmental variable by typing the following code in R: `usethis::edit_r_environ()`. This command uses the function `edit_r_environ()` from the package called `usethis`. If you have not installed the package, first type `install.packages("usethis")` to install the package. Then, add a line `STATISTICS_JAPAN_API_KEY = "your_key_here"`. And save the file. Restart the R kernel.
  
### RStudio

We will be working with packages designed to process and visualize geospatial data. You can install a package by typing the following into the console: `install.packages("package_name")`. *Note the quotations*. Please install the following packages on the computer you will be using: 

- `sf`: simple features a package with many utilities for working with spatial vector data
- `raster`: a package for working with raster data
- `mapview`: a package for creating interactive maps of vector and raster data
- `ggplot`: a package for plotting data (included in tidyverse)

*Note that you do not need to install packages if they are already installed - you only need to install packages once.*



## Geospatial Data Overview:
- **Definition**: Geospatial data is data that includes location information, meaning it includes data linked to locations on the Earth's surface. Geospatial data is usually represented as coordinates (latitude, longitude) or as addresses, regions, or other geographic identifiers.

- **Types of Geospatial Data**:
  - **Vector data**: Represents geographic features using points, lines, and polygons (e.g., locations of stores, roads, or regions).
  - **Raster data**: Represents data in a grid format, typically used for continuous variables (e.g., elevation, temperature, satellite imagery).
- **Coordinate Reference Systems (CRS)**: Defines how spatial data is mapped onto the Earth's surface. It's crucial to understand CRS when working with multiple datasets to ensure they align correctly (e.g., WGS 84, UTM).
- **Projections**: Geospatial data must be projected to represent the 3D Earth on a 2D surface. Different projections minimize different types of distortions (e.g., area, shape, distance).
- **Geospatial Packages in R**:
  - **sf**: Simple Features for R, a package for working with vector data.
  - **raster**: A package for working with raster data.
  - **sp**: An older package that also handles spatial data but is being gradually replaced by `sf`.
- **Common Tasks**:
  - Loading and visualizing geospatial data.
  - Transforming data to different CRS.
  - Performing spatial operations like intersections, unions, and buffers.
  - Creating maps and conducting spatial analysis (e.g., proximity analysis, clustering).
- **File Formats**:
  - **Shapefiles**: A common vector data format that consists of multiple files.
  - **GeoTIFF**: A common raster data format.
  - **GeoJSON**: A lightweight format for sharing geospatial data online.

## Getting started

Let's get some data and read it into R. The Geospatial Information Authority of Japan seems provides downloadable maps of the country:
<https://www.gsi.go.jp/kankyochiri/gm_japan_e.html>. Download the Global Map Japan version 2.2 Vector data (Released in 2016) by clicking on the linked file: gm-jpn-all_u_2_2.zip (9.2MB). This is a zipped file containing many files. **Note where you download the file**. Unzip the file. 

Open up Rstudio. 


